packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.37.0
  prettier: ^3.6.2
  typescript: ^5.9.3

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@sentry/cli"
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - unrs-resolver
