onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - bufferutil
  - esbuild
  - unrs-resolver
overrides:
  "@vitejs/plugin-react": "npm:@vitejs/plugin-react-oxc@latest"
  "vite": "npm:rolldown-vite@latest"
