name: 🔎 CI checks

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-24.04
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: ▫️ Setup pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: ⎔ Setup node
        uses: actions/setup-node@v5.0.0
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      - name: 📥 Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: 🔬 Lint
        run: pnpm run lint

  format:
    name: 🎨 Prettier
    runs-on: ubuntu-24.04
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: ▫️ Setup pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: ⎔ Setup node
        uses: actions/setup-node@v5.0.0
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      - name: 📥 Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: 🎨 Format
        run: pnpm run format

  typecheck:
    name: 🛠️ TypeScript
    runs-on: ubuntu-24.04
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: ▫️ Setup pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: ⎔ Setup node
        uses: actions/setup-node@v5.0.0
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      - name: 📥 Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: 🛠️ Typecheck
        run: pnpm run typecheck
